networks:
  mgmt:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-1
    ipam:
      config:
      - subnet: 172.30.0.0/24
  source-xrd-1:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-2
    ipam:
      config:
      - subnet: 10.1.1.0/24
  xrd-1-gi1-xrd-2-gi0:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-0
    internal: true
    name: xrd-1-gi1-xrd-2-gi0
  xrd-2-dest:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-3
    ipam:
      config:
      - subnet: 10.3.1.0/24
services:
  dest:
    cap_add:
    - NET_ADMIN
    command: /bin/bash -c "ip route add 10.0.0.0/8 via 10.3.1.2 && /bin/bash"
    container_name: dest
    image: ubuntu:14.04
    networks:
      xrd-2-dest:
        ipv4_address: 10.3.1.3
    stdin_open: true
    tty: true
  source:
    cap_add:
    - NET_ADMIN
    command: /bin/bash -c "ip route add 10.0.0.0/8 via 10.1.1.3 && /bin/bash"
    container_name: source
    image: ubuntu:14.04
    networks:
      source-xrd-1:
        ipv4_address: 10.1.1.2
    stdin_open: true
    tty: true
  xrd-1:
    cap_add:
    - CHOWN
    - DAC_OVERRIDE
    - FSETID
    - FOWNER
    - MKNOD
    - NET_RAW
    - SETGID
    - SETUID
    - SETFCAP
    - SETPCAP
    - NET_BIND_SERVICE
    - SYS_CHROOT
    - KILL
    - AUDIT_WRITE
    - SYS_NICE
    - SYS_ADMIN
    - SYS_RESOURCE
    - NET_ADMIN
    - SYS_PTRACE
    - IPC_LOCK
    - SYS_RAWIO
    cap_drop:
    - all
    container_name: xrd-1
    devices:
    - /dev/fuse
    - /dev/net/tun
    environment:
      XR_EVERY_BOOT_CONFIG: /etc/xrd/startup.cfg
      XR_INTERFACES: linux:xr-20,xr_name=Gi0/0/0/0,chksum;linux:xr-00,xr_name=Gi0/0/0/1
      XR_MGMT_INTERFACES: linux:xr-10,xr_name=Mg0/RP0/CPU0/0,chksum
    image: ios-xr/xrd-control-plane:7.9.1
    networks:
      mgmt:
        ipv4_address: 172.30.0.2
      source-xrd-1:
        ipv4_address: 10.1.1.3
      xrd-1-gi1-xrd-2-gi0: null
    security_opt:
    - apparmor:unconfined
    - label:disable
    stdin_open: true
    tty: true
    volumes:
    - source: ./samples/simple-bgp/xrd-1_xrconf.cfg
      target: /etc/xrd/startup.cfg
      type: bind
    - xrd-1:/xr-storage/
  xrd-2:
    cap_add:
    - CHOWN
    - DAC_OVERRIDE
    - FSETID
    - FOWNER
    - MKNOD
    - NET_RAW
    - SETGID
    - SETUID
    - SETFCAP
    - SETPCAP
    - NET_BIND_SERVICE
    - SYS_CHROOT
    - KILL
    - AUDIT_WRITE
    - SYS_NICE
    - SYS_ADMIN
    - SYS_RESOURCE
    - NET_ADMIN
    - SYS_PTRACE
    - IPC_LOCK
    - SYS_RAWIO
    cap_drop:
    - all
    container_name: xrd-2
    devices:
    - /dev/fuse
    - /dev/net/tun
    environment:
      XR_EVERY_BOOT_CONFIG: /etc/xrd/startup.cfg
      XR_INTERFACES: linux:xr-00,xr_name=Gi0/0/0/0;linux:xr-30,xr_name=Gi0/0/0/1,chksum
      XR_MGMT_INTERFACES: linux:xr-10,xr_name=Mg0/RP0/CPU0/0,chksum
    image: ios-xr/xrd-control-plane:7.9.1
    networks:
      mgmt:
        ipv4_address: 172.30.0.3
      xrd-1-gi1-xrd-2-gi0: null
      xrd-2-dest:
        ipv4_address: 10.3.1.2
    security_opt:
    - apparmor:unconfined
    - label:disable
    stdin_open: true
    tty: true
    volumes:
    - source: ./samples/simple-bgp/xrd-2_xrconf.cfg
      target: /etc/xrd/startup.cfg
      type: bind
    - xrd-2:/xr-storage/
version: '2.4'
volumes:
  xrd-1:
    name: xrd-1
  xrd-2:
    name: xrd-2
