version: '3.8'

services:
  flask-app:
    build: .
    container_name: flask_ssh_controller
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    command: flask run --host=0.0.0.0 --port=5000
    networks:
      - ios-xr-streaming-telemetry-demo_mgmt

networks:
  ios-xr-streaming-telemetry-demo_mgmt:
    external: true
