{
 "title": "Streaming Telemetry Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Packet Discards",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "xrd_1_ifcounters_out_discards{name=\"MgmtEth0/RP0/CPU0/0\"}",
     "legendFormat": "xrd-1 MgmtEth0/RP0/CPU0/0"
    },
    {
     "expr": "xrd_2_ifcounters_out_discards{name=\"MgmtEth0/RP0/CPU0/0\"}",
     "legendFormat": "xrd-2 MgmtEth0/RP0/CPU0/0"
    }
   ]
  },
  {
   "title": "Multicast packets",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "xrd_1_ifcounters_in_multicast_pkts{name=\"MgmtEth0/RP0/CPU0/0\"}",
     "legendFormat": "xrd-1  MgmtEth0/RP0/CPU0/0 MgmtEth0/RP0/CPU0/0"
    },
    {
     "expr": "xrd_2_ifcounters_in_multicast_pkts{name=\"MgmtEth0/RP0/CPU0/0\"}",
     "legendFormat": "xrd-2  MgmtEth0/RP0/CPU0/0"
    }
   ]
  },
  {
   "title": "Input Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "xrd_1_ifcounters_in_pkts{name=\"MgmtEth0/RP0/CPU0/0\"}",
     "legendFormat": "xrd-1  MgmtEth0/RP0/CPU0/0"
    },
    {
     "expr": "xrd_2_ifcounters_in_pkts{name=\"MgmtEth0/RP0/CPU0/0\"}",
     "legendFormat": "xrd-2  MgmtEth0/RP0/CPU0/0"
    }
   ]
  }
 ]
}